version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aaa
      - MONGO_INITDB_ROOT_PASSWORD=ccc
      - MONGO_INITDB_DATABASE=admin
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=bbb
      - ME_CONFIG_BASICAUTH_PASSWORD=bbb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN:true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=aaa
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ccc
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - useBasicAuth=true
      
volumes:
  data: {}
networks:
  default:
    name: mongodb_network